name: Publish Submission

on:
  pull_request_target:
    paths:
      - submissions/*.py
    types:
      - closed

jobs:

  publish-submission:
  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: (Re)Evaluation
      timeout-minutes: 5
      run: |
        python test_strategy.py --author ${{ github.event.pull_request.user.login }} --catch-errors --publish --summary $GITHUB_STEP_SUMMARY
      
    - name: Commit updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git commit -m "Publishing ${{ github.event.pull_request.user.login }}'s solution."
        git push